import { useEffect, useRef, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { useNavigate, useParams, useSearchParams } from "react-router-dom";
import jsPDF from "jspdf";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Separator } from "@/components/ui/separator";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { mediHumanJson } from "@/lib/medibondhuHuman";
import { queryKeys } from "@/lib/queryClient";
import { ArrowLeft, Download, Loader2 } from "lucide-react";
import { MB } from "@/components/medibondhu/MediChrome";
import { toast } from "sonner";

type Item = { id: string; medication_name: string | null; dosage: string | null; notes: string | null };
type PrescriptionData = Record<string, unknown> & { items?: Item[] };

type MediPrescriptionPdfInput = {
  doctorName: string;
  doctorQualification: string;
  specialtyName: string;
  chamberAddress: string;
  shortPrescriptionReference: string;
  issuedDate: string;
  prescriptionStatus: string;
  patientUserId: string;
  appointmentId: string;
  consultationMethod: string;
  paidDisplay: string;
  diagnosis: string;
  advice: string;
  followUpDate: string;
  items: Item[];
};

const PDF_CYAN: [number, number, number] = [18, 194, 214];
const PDF_CYAN_DARK: [number, number, number] = [8, 145, 165];
const PDF_CYAN_SOFT: [number, number, number] = [231, 251, 254];
const PDF_BORDER: [number, number, number] = [185, 230, 238];
const PDF_TEXT: [number, number, number] = [17, 24, 39];
const PDF_MUTED: [number, number, number] = [100, 116, 139];

function displayValue(value: unknown, fallback = "N/A") {
  const text = String(value ?? "").trim();
  return text || fallback;
}

function displayShortId(value: unknown) {
  const text = displayValue(value);
  return text === "N/A" ? text : text.slice(-6);
}

function displayLabel(value: unknown) {
  const text = displayValue(value);
  if (text === "N/A") return text;
  return text.replace(/_/g, " ").replace(/\b\w/g, (char) => char.toUpperCase());
}

function displayMoney(value: unknown) {
  const text = String(value ?? "").trim();
  if (!text) return "N/A";
  const amount = Number(text);
  if (!Number.isFinite(amount)) return text;
  return `৳${amount.toLocaleString("en-US")}`;
}

function formatDate(value: unknown) {
  const text = String(value || "").trim();
  if (!text) return "N/A";
  const date = new Date(text);
  return Number.isNaN(date.getTime()) ? text : date.toLocaleDateString(undefined, { dateStyle: "long" });
}

function createMediPdfInput(data: PrescriptionData): MediPrescriptionPdfInput {
  return {
    doctorName: displayValue(data.doctor_name),
    doctorQualification: displayValue(data.doctor_qualification),
    specialtyName: displayValue(data.specialty_name),
    chamberAddress: displayValue(data.doctor_chamber_address),
    shortPrescriptionReference: displayShortId(data.id),
    issuedDate: formatDate(data.created_at),
    prescriptionStatus: displayLabel(data.status),
    patientUserId: displayShortId(data.patient_user_id),
    appointmentId: displayShortId(data.appointment_id),
    consultationMethod: displayLabel(data.appointment_consultation_type),
    paidDisplay: `Paid: ${displayMoney(data.consultation_amount)}`,
    diagnosis: displayValue(data.diagnosis),
    advice: displayValue(data.advice),
    followUpDate: formatDate(data.follow_up_date),
    items: data.items || [],
  };
}

function pdfText(value: string) {
  return value.replace(/৳/g, "BDT ");
}

function buildMediPrescriptionPdfBlob(input: MediPrescriptionPdfInput) {
  const pdf = new jsPDF("p", "mm", "a4");
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 14;
  const contentWidth = pageWidth - margin * 2;
  const footerY = pageHeight - 10;
  let y = margin;

  const setText = () => pdf.setTextColor(...PDF_TEXT);
  const setMuted = () => pdf.setTextColor(...PDF_MUTED);
  const drawFooter = () => {
    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(8);
    setMuted();
    pdf.text("This prescription is online generated by MediBondhu.", pageWidth / 2, footerY, { align: "center" });
    pdf.text(`Page ${pdf.getNumberOfPages()}`, pageWidth - margin, footerY, { align: "right" });
  };
  const addPageIfNeeded = (neededHeight: number) => {
    if (y + neededHeight <= footerY - 8) return;
    drawFooter();
    pdf.addPage();
    y = margin;
  };
  const labelValue = (label: string, value: string, x: number, valueX: number, rowY: number, maxWidth: number) => {
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(8);
    setMuted();
    pdf.text(label, x, rowY);
    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(9);
    setText();
    pdf.text(pdfText(value), valueX, rowY, { maxWidth });
  };
  const sectionTitle = (title: string) => {
    addPageIfNeeded(10);
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(9);
    pdf.setTextColor(...PDF_CYAN_DARK);
    pdf.text(title.toUpperCase(), margin, y);
    y += 5;
  };
  const textBox = (title: string, value: string) => {
    const lines = pdf.splitTextToSize(pdfText(value), contentWidth - 12) as string[];
    const height = Math.max(24, 12 + lines.length * 4.8);
    addPageIfNeeded(height + 3);
    pdf.setDrawColor(...PDF_BORDER);
    pdf.setFillColor(...PDF_CYAN_SOFT);
    pdf.roundedRect(margin, y, contentWidth, height, 3, 3, "FD");
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(8);
    setMuted();
    pdf.text(title, margin + 6, y + 7);
    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(10);
    setText();
    pdf.text(lines, margin + 6, y + 14);
    y += height + 6;
  };
  const clinicalSummaryBoxes = () => {
    const gap = 6;
    const boxWidth = (contentWidth - gap) / 2;
    const diagnosisLines = pdf.splitTextToSize(pdfText(input.diagnosis), boxWidth - 12) as string[];
    const adviceLines = pdf.splitTextToSize(pdfText(input.advice), boxWidth - 12) as string[];
    const height = Math.max(30, 13 + Math.max(diagnosisLines.length, adviceLines.length) * 4.8);
    addPageIfNeeded(height + 3);

    const drawBox = (x: number, title: string, lines: string[]) => {
      pdf.setDrawColor(...PDF_BORDER);
      pdf.setFillColor(...PDF_CYAN_SOFT);
      pdf.roundedRect(x, y, boxWidth, height, 3, 3, "FD");
      pdf.setFont("helvetica", "bold");
      pdf.setFontSize(8);
      setMuted();
      pdf.text(title, x + 6, y + 7);
      pdf.setFont("helvetica", "normal");
      pdf.setFontSize(10);
      setText();
      pdf.text(lines, x + 6, y + 15);
    };

    drawBox(margin, "Diagnosis", diagnosisLines);
    drawBox(margin + boxWidth + gap, "Advice", adviceLines);
    y += height + 8;
  };

  const headerHeight = 46;
  const headerTitleX = margin + 76;
  const headerDoctorX = pageWidth - margin - 4;
  pdf.setDrawColor(226, 232, 240);
  pdf.setFillColor(248, 250, 252);
  pdf.rect(margin, y, contentWidth, headerHeight, "FD");
  pdf.setDrawColor(226, 232, 240);
  pdf.setFillColor(255, 255, 255);
  pdf.roundedRect(margin + 4, y + 6, 64, 17, 8, 8, "FD");
  pdf.setFillColor(...PDF_CYAN);
  pdf.circle(margin + 13, y + 14.5, 7, "F");
  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(8.5);
  pdf.setTextColor(255, 255, 255);
  pdf.text("MB", margin + 13, y + 17.3, { align: "center" });
  pdf.setFontSize(11.5);
  pdf.setTextColor(...PDF_CYAN_DARK);
  pdf.text("MediBondhu", margin + 23, y + 16.5);
  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(7.5);
  setMuted();
  pdf.text("HUMAN CARE", headerTitleX, y + 8);
  pdf.setFontSize(16);
  setText();
  pdf.text("Digital Prescription", headerTitleX, y + 18);
  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(8.5);
  setMuted();
  pdf.text(`Issued ${pdfText(input.issuedDate)}`, headerTitleX, y + 25);
  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(10);
  setText();
  pdf.text(pdfText(input.doctorName), headerDoctorX, y + 9, { align: "right", maxWidth: 62 });
  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(8);
  setMuted();
  pdf.text(pdfText(input.doctorQualification), headerDoctorX, y + 16, { align: "right", maxWidth: 62 });
  pdf.text(pdfText(input.specialtyName), headerDoctorX, y + 21, { align: "right", maxWidth: 62 });
  pdf.text(pdfText(input.chamberAddress), headerDoctorX, y + 26, { align: "right", maxWidth: 62 });
  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(7.5);
  pdf.text(`Ref: ${pdfText(input.shortPrescriptionReference)}`, headerDoctorX, y + 34, { align: "right" });
  y += headerHeight + 12;

  sectionTitle("Prescription details");
  const colWidth = (contentWidth - 6) / 2;
  const detailsHeight = 43;
  pdf.setDrawColor(...PDF_BORDER);
  pdf.setFillColor(250, 253, 254);
  pdf.roundedRect(margin, y, colWidth, detailsHeight, 3, 3, "FD");
  pdf.roundedRect(margin + colWidth + 6, y, colWidth, detailsHeight, 3, 3, "FD");
  labelValue("Patient user ID", input.patientUserId, margin + 5, margin + 44, y + 8, 36);
  labelValue("Appointment ID", input.appointmentId, margin + 5, margin + 44, y + 18, 36);
  labelValue("Referral ID", input.shortPrescriptionReference, margin + 5, margin + 44, y + 28, 36);
  const rightX = margin + colWidth + 11;
  labelValue("Issued date", input.issuedDate, rightX, rightX + 32, y + 8, 48);
  labelValue("Status", input.prescriptionStatus, rightX, rightX + 32, y + 18, 48);
  labelValue("Method", input.consultationMethod, rightX, rightX + 32, y + 28, 48);
  labelValue("Payment", input.paidDisplay, rightX, rightX + 32, y + 38, 48);
  y += detailsHeight + 10;

  sectionTitle("Clinical summary");
  clinicalSummaryBoxes();

  sectionTitle("Medications");
  const rows = input.items.length ? input.items : [{ id: "empty", medication_name: "N/A", dosage: "N/A", notes: "N/A" }];
  const tableX = margin;
  const colDrug = 54;
  const colDose = 42;
  const colNotes = contentWidth - colDrug - colDose;
  const drawMedicationHeader = () => {
    addPageIfNeeded(13);
    pdf.setDrawColor(...PDF_BORDER);
    pdf.setFillColor(...PDF_CYAN_SOFT);
    pdf.rect(tableX, y, contentWidth, 9, "FD");
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(8);
    setText();
    pdf.text("Drug", tableX + 3, y + 6);
    pdf.text("Dosage", tableX + colDrug + 3, y + 6);
    pdf.text("Notes", tableX + colDrug + colDose + 3, y + 6);
    y += 9;
  };
  drawMedicationHeader();
  rows.forEach((item) => {
    const drugLines = pdf.splitTextToSize(pdfText(displayValue(item.medication_name)), colDrug - 6) as string[];
    const doseLines = pdf.splitTextToSize(pdfText(displayValue(item.dosage)), colDose - 6) as string[];
    const noteLines = pdf.splitTextToSize(pdfText(displayValue(item.notes)), colNotes - 6) as string[];
    const lineCount = Math.max(drugLines.length, doseLines.length, noteLines.length);
    const rowHeight = Math.max(10, 5 + lineCount * 4.2);
    if (y + rowHeight > footerY - 8) {
      drawFooter();
      pdf.addPage();
      y = margin;
      drawMedicationHeader();
    }
    pdf.setDrawColor(226, 232, 240);
    pdf.rect(tableX, y, colDrug, rowHeight);
    pdf.rect(tableX + colDrug, y, colDose, rowHeight);
    pdf.rect(tableX + colDrug + colDose, y, colNotes, rowHeight);
    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(8.5);
    setText();
    pdf.text(drugLines, tableX + 3, y + 5);
    pdf.text(doseLines, tableX + colDrug + 3, y + 5);
    pdf.text(noteLines, tableX + colDrug + colDose + 3, y + 5);
    y += rowHeight;
  });
  y += 8;

  sectionTitle("Follow-up");
  textBox("Suggested follow-up date", input.followUpDate);
  drawFooter();

  return pdf.output("blob");
}

export default function PrescriptionDetailHuman() {
  const { id } = useParams();
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const autoPreviewOpenedRef = useRef(false);
  const [isGeneratingPreview, setIsGeneratingPreview] = useState(false);
  const [pdfPreviewUrl, setPdfPreviewUrl] = useState<string | null>(null);
  const shouldAutoPreview = searchParams.get("preview") === "1";

  const { data, isLoading } = useQuery({
    queryKey: queryKeys().medibondhuHumanPrescriptionDetail(id),
    enabled: Boolean(id),
    queryFn: async () => {
      const { res, body } = await mediHumanJson<{ data?: PrescriptionData }>(`/prescriptions/${id}`);
      if (!res.ok) throw new Error(String((body as { error?: string }).error || res.status));
      return body.data;
    },
  });

  useEffect(() => {
    return () => {
      if (pdfPreviewUrl) URL.revokeObjectURL(pdfPreviewUrl);
    };
  }, [pdfPreviewUrl]);

  useEffect(() => {
    if (!shouldAutoPreview || !data || autoPreviewOpenedRef.current) return;
    autoPreviewOpenedRef.current = true;
    setIsGeneratingPreview(true);
    try {
      const blob = buildMediPrescriptionPdfBlob(createMediPdfInput(data));
      setPdfPreviewUrl(URL.createObjectURL(blob));
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "Could not preview prescription PDF");
    } finally {
      setIsGeneratingPreview(false);
    }
  }, [data, shouldAutoPreview]);

  if (isLoading) {
    return <p className="text-center py-16 text-muted-foreground text-sm">Loading prescription…</p>;
  }

  if (!data) {
    return (
      <div className="max-w-lg mx-auto text-center py-16 px-4">
        <p className="font-medium text-foreground">Prescription not found</p>
        <Button type="button" variant="outline" className="mt-4 rounded-xl" onClick={() => navigate("/medibondhu/prescriptions")}>
          Back to list
        </Button>
      </div>
    );
  }

  const pdfInput = createMediPdfInput(data);
  const items = pdfInput.items;
  const created = data.created_at ? String(data.created_at) : null;
  const doctorName = pdfInput.doctorName;
  const doctorQualification = pdfInput.doctorQualification;
  const specialtyName = pdfInput.specialtyName;
  const chamberAddress = pdfInput.chamberAddress;
  const shortPrescriptionReference = pdfInput.shortPrescriptionReference;
  const issuedDate = pdfInput.issuedDate;
  const prescriptionStatus = pdfInput.prescriptionStatus;
  const patientUserId = pdfInput.patientUserId;
  const appointmentId = pdfInput.appointmentId;
  const consultationMethod = pdfInput.consultationMethod;
  const paidDisplay = pdfInput.paidDisplay;
  const pdfFilename = `medibondhu-prescription-${shortPrescriptionReference}.pdf`;

  const handlePreviewPdf = async () => {
    setIsGeneratingPreview(true);
    try {
      const blob = buildMediPrescriptionPdfBlob(pdfInput);
      setPdfPreviewUrl(URL.createObjectURL(blob));
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "Could not preview prescription PDF");
    } finally {
      setIsGeneratingPreview(false);
    }
  };

  const handleDownloadPreview = () => {
    if (!pdfPreviewUrl) return;
    const link = document.createElement("a");
    link.href = pdfPreviewUrl;
    link.download = pdfFilename;
    link.click();
    toast.success("Prescription PDF downloaded");
  };

  return (
    <div className="space-y-6 max-w-3xl mx-auto">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <Button type="button" variant="ghost" className="gap-2 -ml-2 self-start" onClick={() => navigate("/medibondhu/prescriptions")}>
          <ArrowLeft className="h-4 w-4" /> Prescriptions
        </Button>
        <Button type="button" className="gap-2 self-start" style={{ backgroundColor: MB }} disabled={isGeneratingPreview} onClick={() => void handlePreviewPdf()}>
          {isGeneratingPreview ? <Loader2 className="h-4 w-4 animate-spin" /> : <Download className="h-4 w-4" />}
          {isGeneratingPreview ? "Generating..." : "Preview PDF"}
        </Button>
      </div>

      <Card className="rounded-2xl overflow-hidden border-border shadow-md print:shadow-none">
        <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-5 px-6 md:px-8 py-6 border-b bg-muted/20">
          <div className="flex items-start gap-3">
            <div className="inline-flex items-center gap-2 rounded-full bg-white px-2.5 py-1.5 shadow-sm ring-1 ring-border">
              <span className="flex h-9 w-9 items-center justify-center rounded-full text-xs font-bold text-white" style={{ backgroundColor: MB }}>
                MB
              </span>
              <span className="pr-2 text-sm font-bold" style={{ color: MB }}>
                MediBondhu
              </span>
            </div>
            <div>
              <p className="text-xs font-semibold uppercase tracking-[0.2em] text-muted-foreground">Human care</p>
              <h1 className="text-2xl font-display font-bold text-foreground mt-0.5">Digital Prescription</h1>
              <p className="text-sm text-muted-foreground mt-1">Issued {created ? new Date(created).toLocaleString() : "N/A"}</p>
            </div>
          </div>
          <div className="text-left sm:text-right text-sm">
            <p className="font-semibold text-foreground">{doctorName}</p>
            <p className="text-muted-foreground">{doctorQualification}</p>
            <p className="text-muted-foreground">{specialtyName}</p>
            <p className="text-muted-foreground">{chamberAddress}</p>
            <p className="font-mono text-xs break-all opacity-70">Ref: {shortPrescriptionReference}</p>
          </div>
        </div>

        <CardContent className="p-6 md:p-8 space-y-8">
          <section className="rounded-xl border p-4" style={{ borderColor: `${MB}24`, backgroundColor: `${MB}0D` }}>
            <h2 className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Prescription details</h2>
            <div className="mt-4 grid gap-4 sm:grid-cols-2">
              <div className="space-y-3 rounded-lg border bg-background/70 p-3">
                <div>
                  <p className="text-xs text-muted-foreground">Patient user ID</p>
                  <p className="mt-1 font-mono text-xs break-all text-foreground">{patientUserId}</p>
                </div>
                <div>
                  <p className="text-xs text-muted-foreground">Appointment ID</p>
                  <p className="mt-1 font-mono text-xs break-all text-foreground">{appointmentId}</p>
                </div>
                <div>
                  <p className="text-xs text-muted-foreground">Referral ID</p>
                  <p className="mt-1 font-mono text-xs break-all text-foreground">{shortPrescriptionReference}</p>
                </div>
              </div>
              <div className="space-y-3 rounded-lg border bg-background/70 p-3">
                <div>
                  <p className="text-xs text-muted-foreground">Issued date</p>
                  <p className="mt-1 text-sm font-medium text-foreground">{issuedDate}</p>
                </div>
                <div>
                  <p className="text-xs text-muted-foreground">Status</p>
                  <p className="mt-1 text-sm font-medium text-foreground">{prescriptionStatus}</p>
                </div>
                <div>
                  <p className="text-xs text-muted-foreground">Method</p>
                  <p className="mt-1 text-sm font-medium text-foreground">{consultationMethod}</p>
                </div>
                <div>
                  <p className="text-xs text-muted-foreground">Payment</p>
                  <p className="mt-1 text-sm font-medium text-foreground">{paidDisplay}</p>
                </div>
              </div>
            </div>
          </section>

          <section className="space-y-3">
            <h2 className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Clinical summary</h2>
            <div className="grid gap-6 sm:grid-cols-2">
              <div
                className="rounded-xl border p-4"
                style={{ borderColor: `${MB}2F`, backgroundColor: `${MB}14` }}
              >
                <p className="text-xs text-muted-foreground mb-1">Diagnosis</p>
                <p className="text-sm leading-relaxed text-foreground whitespace-pre-wrap">{displayValue(data.diagnosis)}</p>
              </div>
              <div
                className="rounded-xl border p-4"
                style={{ borderColor: `${MB}2F`, backgroundColor: `${MB}14` }}
              >
                <p className="text-xs text-muted-foreground mb-1">Advice</p>
                <p className="text-sm leading-relaxed text-foreground whitespace-pre-wrap">{displayValue(data.advice)}</p>
              </div>
            </div>
          </section>

          <section>
            <h2 className="text-xs font-semibold uppercase tracking-wider text-muted-foreground mb-4">Medications</h2>
            {items.length > 0 ? (
              <div className="rounded-xl border overflow-hidden">
                <Table>
                  <TableHeader>
                    <TableRow className="bg-muted/50 hover:bg-muted/50">
                      <TableHead className="font-semibold">Drug</TableHead>
                      <TableHead className="font-semibold w-[28%]">Dosage</TableHead>
                      <TableHead className="font-semibold">Notes</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {items.map((it, index) => (
                      <TableRow key={it.id || `medication-${index}`}>
                        <TableCell className="font-medium align-top">{displayValue(it.medication_name)}</TableCell>
                        <TableCell className="text-muted-foreground align-top">{displayValue(it.dosage)}</TableCell>
                        <TableCell className="text-sm text-muted-foreground align-top">{displayValue(it.notes)}</TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              </div>
            ) : (
              <div className="rounded-xl border overflow-hidden">
                <Table>
                  <TableHeader>
                    <TableRow className="bg-muted/50 hover:bg-muted/50">
                      <TableHead className="font-semibold">Drug</TableHead>
                      <TableHead className="font-semibold w-[28%]">Dosage</TableHead>
                      <TableHead className="font-semibold">Notes</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    <TableRow>
                      <TableCell className="font-medium align-top">N/A</TableCell>
                      <TableCell className="text-muted-foreground align-top">N/A</TableCell>
                      <TableCell className="text-sm text-muted-foreground align-top">N/A</TableCell>
                    </TableRow>
                  </TableBody>
                </Table>
              </div>
            )}
          </section>

          <Separator />

          <section className="rounded-xl border bg-muted/10 p-4">
            <h2 className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Follow-up</h2>
            <p className="mt-2 text-sm">
              <span className="text-muted-foreground">Suggested follow-up date: </span>
              <span className="font-medium text-foreground">{formatDate(data.follow_up_date)}</span>
            </p>
          </section>

          <p className="text-center text-xs text-muted-foreground leading-relaxed border-t pt-6">
            This prescription is online generated by MediBondhu.
          </p>
        </CardContent>
      </Card>

      <Dialog open={Boolean(pdfPreviewUrl)} onOpenChange={(open) => !open && setPdfPreviewUrl(null)}>
        <DialogContent className="max-w-5xl">
          <DialogHeader>
            <DialogTitle>MediBondhu prescription PDF preview</DialogTitle>
            <DialogDescription>Review the generated prescription PDF, then download it when ready.</DialogDescription>
          </DialogHeader>
          <div className="h-[70vh] overflow-hidden rounded-xl border bg-muted/20">
            {pdfPreviewUrl ? <iframe src={pdfPreviewUrl} title="MediBondhu prescription PDF preview" className="h-full w-full bg-white" /> : null}
          </div>
          <DialogFooter>
            <Button type="button" variant="outline" onClick={() => setPdfPreviewUrl(null)}>
              Close
            </Button>
            <Button type="button" className="gap-2" style={{ backgroundColor: MB }} onClick={handleDownloadPreview}>
              <Download className="h-4 w-4" />
              Download PDF
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
