import jsPDF from "jspdf";

export type SalesMemoLine = {
  id: string;
  date: string;
  product: string;
  category: string;
  quantity: number;
  unit: string;
  unitPrice: number;
  lineTotal: number;
};

export type SalesMemoDraft = {
  memoNo: string;
  memoDate: string;
  buyerName: string;
  farm: {
    name: string;
    type: string;
    location?: string;
    phone?: string;
    email?: string;
  };
  items: SalesMemoLine[];
  grandTotal: number;
  footerNote?: string;
};

const HEADER_RGB: [number, number, number] = [22, 78, 55];
const BADGE_RGB: [number, number, number] = [34, 110, 80];
export const DEFAULT_SALES_MEMO_FOOTER =
  "* Goods once sold are not returnable unless defective.\nThank you for your purchase!";

const CAT_LABELS: Record<string, string> = {
  eggs: "Eggs",
  milk: "Milk",
  meat: "Meat",
  live_animals: "Live Animals",
};

export function createSalesMemoNo(): string {
  return `MEMO-${Date.now().toString(36).toUpperCase()}`;
}

export function formatSalesMemoPdfAmount(amount: number): string {
  const n = Math.round(Number(amount) || 0);
  return `BDT ${n.toLocaleString("en-US")}`;
}

const MEMO_DATE_OPTS: Intl.DateTimeFormatOptions = {
  day: "numeric",
  month: "short",
  year: "numeric",
};

export function formatMemoDateDisplay(isoOrDate: string): string {
  if (!isoOrDate?.trim()) return "—";
  if (/^\d{4}-\d{2}-\d{2}$/.test(isoOrDate)) {
    const [y, m, d] = isoOrDate.split("-").map(Number);
    return new Date(y, m - 1, d).toLocaleDateString("en-GB", MEMO_DATE_OPTS);
  }
  const parsed = new Date(isoOrDate);
  if (Number.isNaN(parsed.getTime())) return isoOrDate;
  return parsed.toLocaleDateString("en-GB", MEMO_DATE_OPTS);
}

/** Short en-GB date for table rows (never raw ISO). */
export function formatSaleLineDate(date: string): string {
  return formatMemoDateDisplay(date);
}

function farmTypeLabel(type: string): string {
  const t = type.trim() || "farm";
  return `${t.charAt(0).toUpperCase()}${t.slice(1)} Farm`;
}

function categoryLabel(category: string): string {
  return CAT_LABELS[category] || category;
}

export function salesMemoPreviewLines(draft: SalesMemoDraft): {
  farmName: string;
  farmTypeLabel: string;
  memoNo: string;
  contactLines: string[];
  buyerName: string;
  memoDate: string;
  itemCount: number;
  items: { index: number; date: string; product: string; category: string; qty: string; unitPrice: string; lineTotal: string }[];
  grandTotal: string;
  footerLines: string[];
} {
  const contactLines: string[] = [];
  if (draft.farm.location?.trim()) contactLines.push(`Location: ${draft.farm.location.trim()}`);
  if (draft.farm.phone?.trim()) contactLines.push(`Phone: ${draft.farm.phone.trim()}`);
  if (draft.farm.email?.trim()) contactLines.push(`Email: ${draft.farm.email.trim()}`);

  const footerRaw = draft.footerNote?.trim() || DEFAULT_SALES_MEMO_FOOTER;
  const footerLines = [
    ...footerRaw.split("\n").filter(Boolean),
    `Generated by FarmBondhu on ${formatMemoDateDisplay(draft.memoDate)}`,
  ];

  return {
    farmName: draft.farm.name,
    farmTypeLabel: farmTypeLabel(draft.farm.type),
    memoNo: draft.memoNo,
    contactLines,
    buyerName: draft.buyerName.trim() || "—",
    memoDate: formatMemoDateDisplay(draft.memoDate),
    itemCount: draft.items.length,
    items: draft.items.map((item, i) => ({
      index: i + 1,
      date: formatSaleLineDate(item.date),
      product: item.product,
      category: categoryLabel(item.category),
      qty: `${item.quantity} ${item.unit}`,
      unitPrice: formatSalesMemoPdfAmount(item.unitPrice),
      lineTotal: formatSalesMemoPdfAmount(item.lineTotal),
    })),
    grandTotal: formatSalesMemoPdfAmount(draft.grandTotal),
    footerLines,
  };
}

function addSalesMemoContent(doc: jsPDF, draft: SalesMemoDraft): void {
  const pw = doc.internal.pageSize.getWidth();
  const ph = doc.internal.pageSize.getHeight();
  const ml = 15;
  const mr = pw - 15;
  const contentW = mr - ml;
  const preview = salesMemoPreviewLines(draft);
  const farmName = draft.farm.name;
  const [hr, hg, hb] = HEADER_RGB;
  const [br, bg, bb] = BADGE_RGB;

  doc.setFontSize(72);
  doc.setTextColor(240, 245, 240);
  doc.text(farmName.toUpperCase(), pw / 2, ph / 2, { align: "center", angle: 40 });

  doc.setFillColor(hr, hg, hb);
  doc.rect(0, 0, pw, 28, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text(farmName.toUpperCase(), ml + 2, 13);

  const typeLabel = preview.farmTypeLabel;
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  const badgeX = ml + 2;
  const badgeY = 18;
  const badgeW = doc.getTextWidth(typeLabel) + 6;
  doc.setFillColor(br, bg, bb);
  doc.roundedRect(badgeX, badgeY - 3.5, badgeW, 5.5, 1.5, 1.5, "F");
  doc.setTextColor(200, 240, 220);
  doc.text(typeLabel, badgeX + 3, badgeY);

  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("SALES MEMO", mr - 2, 13, { align: "right" });

  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(170, 210, 190);
  doc.text(draft.memoNo, mr - 2, 19, { align: "right" });

  doc.setFillColor(230, 245, 235);
  doc.rect(0, 28, pw, 10, "F");
  doc.setDrawColor(hr, hg, hb);
  doc.setLineWidth(0.3);
  doc.line(0, 38, pw, 38);

  doc.setFontSize(8);
  doc.setTextColor(40, 80, 55);
  if (preview.contactLines.length > 0) {
    doc.text(preview.contactLines.join("    |    "), pw / 2, 34, { align: "center" });
  }

  let y = 44;
  doc.setDrawColor(200, 210, 200);
  doc.setLineWidth(0.4);
  doc.roundedRect(ml, y, contentW, 18, 2, 2, "S");

  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(60, 60, 60);
  doc.text("Buyer:", ml + 4, y + 6);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(33, 33, 33);
  const buyerDisplay = preview.buyerName;
  doc.text(
    buyerDisplay.length > 35 ? `${buyerDisplay.substring(0, 35)}...` : buyerDisplay,
    ml + 20,
    y + 6,
  );

  doc.setFont("helvetica", "bold");
  doc.text("Date:", ml + 4, y + 13);
  doc.setFont("helvetica", "normal");
  doc.text(preview.memoDate, ml + 20, y + 13);

  const midX = pw / 2 + 10;
  doc.setFont("helvetica", "bold");
  doc.text("Items:", midX, y + 6);
  doc.setFont("helvetica", "normal");
  doc.text(`${preview.itemCount}`, midX + 16, y + 6);

  doc.setFont("helvetica", "bold");
  doc.text("Memo #:", midX, y + 13);
  doc.setFont("helvetica", "normal");
  doc.text(draft.memoNo, midX + 20, y + 13);

  y += 24;
  const cols = {
    num: ml,
    date: ml + 10,
    product: ml + 32,
    cat: ml + 82,
    qty: ml + 110,
    price: ml + 130,
    total: ml + 155,
  };
  const rowH = 7;

  doc.setFillColor(hr, hg, hb);
  doc.rect(ml, y, contentW, 8, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  y += 5.5;
  doc.text("#", cols.num + 2, y);
  doc.text("Date", cols.date + 2, y);
  doc.text("Product", cols.product + 2, y);
  doc.text("Category", cols.cat + 2, y);
  doc.text("Qty", cols.qty + 2, y);
  doc.text("Unit Price", cols.price + 2, y);
  doc.text("Total", cols.total + 2, y);
  y += 3.5;

  doc.setFont("helvetica", "normal");
  draft.items.forEach((r, i) => {
    if (y > ph - 50) {
      doc.addPage();
      y = 20;
    }
    if (i % 2 === 0) {
      doc.setFillColor(245, 248, 245);
      doc.rect(ml, y - 1, contentW, rowH, "F");
    }
    doc.setFontSize(8);
    doc.setTextColor(50, 50, 50);
    const rowY = y + 4;
    doc.text(`${i + 1}`, cols.num + 2, rowY);
    const dateLabel = formatSaleLineDate(r.date);
    const maxDateW = cols.product - cols.date - 4;
    const dateLines = doc.splitTextToSize(dateLabel, maxDateW) as string[];
    doc.text(dateLines[0] || dateLabel, cols.date + 2, rowY);

    const maxProductW = cols.cat - cols.product - 4;
    const productLines = doc.splitTextToSize(r.product, maxProductW) as string[];
    doc.text(productLines[0] || r.product, cols.product + 2, rowY);

    const maxCatW = cols.qty - cols.cat - 4;
    const catLines = doc.splitTextToSize(categoryLabel(r.category), maxCatW) as string[];
    doc.text(catLines[0] || r.category, cols.cat + 2, rowY);

    doc.text(`${r.quantity} ${r.unit}`, cols.qty + 2, rowY);
    doc.text(formatSalesMemoPdfAmount(r.unitPrice), cols.price + 2, rowY);

    doc.setFont("helvetica", "bold");
    doc.setTextColor(hr, hg, hb);
    doc.text(formatSalesMemoPdfAmount(r.lineTotal), cols.total + 2, rowY);
    doc.setFont("helvetica", "normal");
    y += rowH;
  });

  doc.setDrawColor(hr, hg, hb);
  doc.setLineWidth(0.5);
  doc.line(ml, y, mr, y);

  y += 6;
  const totalBoxW = 70;
  const totalBoxX = mr - totalBoxW;
  doc.setFillColor(hr, hg, hb);
  doc.roundedRect(totalBoxX, y, totalBoxW, 12, 2, 2, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text(
    `Grand Total: ${formatSalesMemoPdfAmount(draft.grandTotal)}`,
    totalBoxX + totalBoxW / 2,
    y + 8,
    { align: "center" },
  );

  y += 28;
  if (y > ph - 40) {
    doc.addPage();
    y = 30;
  }

  doc.setDrawColor(160, 160, 160);
  doc.setLineWidth(0.3);
  doc.line(ml, y, ml + 60, y);
  doc.setFontSize(8);
  doc.setTextColor(100, 100, 100);
  doc.text("Seller's Signature", ml, y + 5);
  doc.line(mr - 60, y, mr, y);
  doc.text("Buyer's Signature", mr - 60, y + 5);

  y += 16;
  doc.setFontSize(7);
  doc.setTextColor(150, 150, 150);
  preview.footerLines.forEach((line, idx) => {
    doc.text(line, pw / 2, y + idx * 5, { align: "center" });
  });
}

export function buildSalesMemoPdf(draft: SalesMemoDraft): jsPDF {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  addSalesMemoContent(doc, draft);
  return doc;
}

export function getSalesMemoPdfBlob(draft: SalesMemoDraft): Blob {
  return buildSalesMemoPdf(draft).output("blob");
}

export const SALES_MEMO_CATEGORIES = [
  { value: "eggs", label: "Eggs" },
  { value: "milk", label: "Milk" },
  { value: "meat", label: "Meat" },
  { value: "live_animals", label: "Live Animals" },
] as const;

export function downloadSalesMemoPdf(draft: SalesMemoDraft): void {
  const doc = buildSalesMemoPdf(draft);
  const safeName = draft.farm.name.replace(/\s+/g, "_");
  doc.save(`${safeName}_Memo_${draft.memoNo}.pdf`);
}

export function printSalesMemoPdf(draft: SalesMemoDraft): void {
  const doc = buildSalesMemoPdf(draft);
  const blob = doc.output("blob");
  const url = URL.createObjectURL(blob);
  const win = window.open(url);
  if (!win) {
    URL.revokeObjectURL(url);
    throw new Error("Could not open print window. Allow pop-ups and try again.");
  }
  win.onload = () => {
    win.focus();
    win.print();
    URL.revokeObjectURL(url);
  };
}

export const SALES_MEMO_FARM_TYPES = [
  { value: "poultry", label: "Poultry" },
  { value: "dairy", label: "Dairy" },
  { value: "livestock", label: "Livestock" },
  { value: "mixed", label: "Mixed" },
  { value: "crop", label: "Crop" },
  { value: "farm", label: "General Farm" },
] as const;
